Package.swift
Tests/SwiftFusionTests/Core/MatrixTests.swift
Tests/SwiftFusionTests/TestUtilities.swift

Let's not over-engineer and stick with TensorFlow for now :)
~~Mergeable after the test utility function `assertEqual` in #16 is merged.~~
I copied that piece of code from Marc's PR, now mergeable.
This should also reduce compile time from 1 minute to about 10 seconds.

Remove SwiftRT

---

Sources/SwiftFusion/Geometry/Pose2.swift
Sources/SwiftFusion/Geometry/Rot2.swift
Tests/SwiftFusionTests/Geometry/Pose2Tests.swift

Remove inverse method

---

Sources/SwiftFusion/Optimizers/NLCG.swift
Tests/SwiftFusionTests/Geometry/Pose2Tests.swift

This implements the golden section search in NLCG.
Also tightened some tolerances in unit tests.

Golden Section Search

---

Sources/SwiftFusion/Optimizers/NLCG.swift

Fix NLCG initialization step

---

Sources/SwiftFusion/Geometry/Rot2.swift

Remove redundant code without test coverage

Remove redundant code without test coverage

---

Sources/SwiftFusion/Core/FixedDimensionVector.swift
Sources/SwiftFusion/Core/VectorN.swift
Sources/SwiftFusion/Core/VectorN.swift.gyb
Tests/SwiftFusionTests/Core/VectorNTests.swift
Tests/SwiftFusionTests/Core/VectorNTests.swift.gyb

A protocol for vectors with compiletime fixed dimension.

fixed dimension vector protocol

---

Sources/SwiftFusion/Core/Matrix.swift
Sources/SwiftFusion/Core/MatrixN.swift
Sources/SwiftFusion/Geometry/Rot3.swift
Tests/SwiftFusionTests/Core/MatrixNTests.swift
Tests/SwiftFusionTests/Core/MatrixTests.swift
Tests/SwiftFusionTests/Geometry/Rot3Tests.swift

This implements the static 3x3 matrix version of Rot3. Pose3SLAM now runs 10x faster :)

Matrix3 for Rot3

---

.github/workflows/ci.yml

There are various AD fixes and speedups in this new toolchain.

update to latest macos toolchain

---

Sources/SwiftFusion/Core/EuclideanVector.swift
Sources/SwiftFusion/Core/Tuple+EuclideanVectorN.swift
Sources/SwiftFusion/Core/Vector.swift
Sources/SwiftFusion/Core/VectorN.swift
Sources/SwiftFusion/Core/VectorN.swift.gyb
Sources/SwiftFusion/Inference/BearingRangeFactor.swift
Sources/SwiftFusion/Inference/BetweenFactor.swift
Sources/SwiftFusion/Inference/FactorsStorage.swift
Sources/SwiftFusion/Inference/GenericFactor.swift
Tests/SwiftFusionTests/Core/EuclideanVectorTests.swift
Tests/SwiftFusionTests/Inference/GenericFactorTests.swift

This adds refined factor protocols "GenericLinearizableFactor" and "GenericGaussianFactor".
The main point is to allow solvers that do iterated linearization. The solver linearizes all the "GenericLinearizableFactors" at the current point to get a bunch of "GenericGaussianFactors", and then it solves the factor graph of "GenericGaussianFactors". (No solver included in this PR).

generic linearizable and gaussian factors

---

Sources/SwiftFusion/Inference/AllVectors.swift
Sources/SwiftFusion/Inference/GaussianFactorGraph.swift
Sources/SwiftFusion/Inference/JacobianFactor.swift
Tests/SwiftFusionTests/Inference/GaussianFactorGraphTests.swift

An example usage is in the test.

method for adding factors to a GaussianFactorGraph

---

Tests/SwiftFusionTests/Geometry/Rot3Tests.swift
Tests/SwiftFusionTests/Inference/FactorGraphTests.swift

* Sometimes the randomized Rot3 tests fail to be within the accepted accuracy. I expanded the accepted range.
* Sometimes the randomized chordal PoseSLAM test fails because it gets stuck in a local minimum (I think?). I added retries.

deflake some tests

---

Sources/SwiftFusion/Geometry/Rot3.swift
Tests/SwiftFusionTests/Geometry/Rot3Tests.swift

This fixes the NaN error detected by #110 .
Kudos to @marcrasi for the awesome NaN detector :)

Fix the NaN in acos() of Rot3 localCoordinate

---

Tests/SwiftFusionTests/Geometry/Pose3Tests.swift
Tests/SwiftFusionTests/Inference/NonlinearFactorGraphTests.swift
Tests/SwiftFusionTests/Optimizers/CGLSTests.swift
Tests/SwiftFusionTests/TestUtilities.swift

Update some tests to new FG

---

Sources/SwiftFusionBenchmarks/Pose3SLAM.swift

Adds some chordal benchmarks to the benchmark suite so that I can quickly and easily get some numbers about how things affect chordal performance.

chordal benchmarks in the suite

---

Sources/SwiftFusion/Core/EuclideanVectorN.swift
Sources/SwiftFusion/Core/FixedShapeTensor.swift
Tests/SwiftFusionTests/Core/FixedShapeTensorTests.swift

These are the comments that should have been included in https://github.com/borglab/SwiftFusion/pull/141.

doc comments for the fixed shape tensor

---

Package.swift
Sources/SwiftFusion/Core/TypeKeyedArrayBuffers.swift
Sources/SwiftFusion/Inference/AllVectors.swift
Sources/SwiftFusion/Inference/ArrayBuffer+Differentiable.swift
Sources/SwiftFusion/Inference/ArrayBuffer+Tensor.swift
Sources/SwiftFusion/Inference/ArrayBuffer+Vector.swift
Sources/SwiftFusion/Inference/ArrayStorage+Tensor.swift
Sources/SwiftFusion/Inference/FactorsStorage.swift
Sources/SwiftFusion/Inference/PenguinExtensions.swift
Sources/SwiftFusion/Inference/ValuesStorage.swift
Tests/SwiftFusionTests/Inference/ValuesStorageTests.swift

Depends on #153.  
ArrayBuffers are differentiable and ArrayBuffers of Vector conform to Vector.
Does not yet make AnyArrayBuffer Differentiable, but all tests pass and the code is better, so I think we should accept in its current form.

Progress toward Differentiable AnyArrayBuffer

---

Package.resolved
Sources/SwiftFusion/Core/FixedShapeTensor.swift
Sources/SwiftFusion/Core/FixedSizeMatrix.swift
Sources/SwiftFusion/Core/Tuple+Vector.swift
Sources/SwiftFusion/Core/Vector.swift
Sources/SwiftFusion/Core/VectorN.swift
Sources/SwiftFusion/Core/VectorN.swift.gyb
Sources/SwiftFusion/Inference/ArrayBuffer+Vector.swift
Sources/SwiftFusion/Inference/FactorBoilerplate.swift
Sources/SwiftFusion/Inference/PenguinExtensions.swift
Sources/SwiftFusion/MCMC/RandomWalkMetropolis.swift
Tests/SwiftFusionTests/Core/VectorNTests.swift
Tests/SwiftFusionTests/MCMC/MCMCTests.swift
generate.sh

All the comments are in and this is ready to land now.

Differentiable scalars

---

Sources/SwiftFusion/Inference/PenguinExtensions.swift
Sources/SwiftFusion/Inference/ValuesStorage.swift

Make master build again

---

Sources/BeeDataset/BeeFrames.swift
Sources/BeeDataset/BeeOrientedBoundingBoxes.swift
Sources/BeeDataset/BeeVideo.swift
Sources/BeeDataset/Download.swift
Tests/BeeDatasetTests/BeeDatasetTests.swift
Util/BeeAnnotations/README.md
Util/BeeAnnotations/annotator.html
Util/BeeAnnotations/app.js

I downloaded one (4-second) bee video and annotated 2 (slow moving, not waggling) bees in it.
This PR adds code for loading the data.
This PR also includes the simple annotation tool that I wrote to do the annotations.
Here is an example notebook that displays the data: https://colab.sandbox.google.com/drive/1M2MRDNWGufFbamZlo3d0dZM-OV5CgE0E#scrollTo=me1CsMBYDm8P

higher resolution bee video

---

Sources/SwiftFusion/Inference/FactorGraph.swift
Sources/SwiftFusion/Inference/FactorsStorage.swift
Sources/SwiftFusion/Optimizers/GradientDescent.swift
Tests/SwiftFusionTests/Inference/FactorGraphTests.swift
Tests/SwiftFusionTests/Optimizers/GradientDescentTests.swift

I included a test on a simple factor graph, but I haven't tried to use it on anything more complicated like the PPCA tracking factor graph. I would expect it to work without any problems.

add a gradient descent factor graph optimizer

---

Examples/BeeTrackingTool/main.swift
Sources/BeeDataset/VOTVideo.swift
Sources/SwiftFusion/Geometry/Rot2.swift

Here's some intermediate progress towards running the tracker on other datasets. This PR loads VOT datasets.
My next step will be to train and run the tracker on some of these sequences to see what happens.
Here's a notebook that loads and displays one frame: https://colab.sandbox.google.com/drive/16t-lAqMk4nFh35P9CeGX8TYfdkuLCYHy

VOT dataset loading

---

Examples/OISTVisualizationTool/main.swift
Package.resolved
Package.swift
Sources/BeeDataset/BeeFrames.swift
Sources/BeeDataset/BeeVideo.swift
Sources/BeeDataset/OISTBeeVideo.swift
Sources/BeeDataset/VOTVideo.swift
Sources/BeeDataset/Visualization.swift
Tests/SwiftFusionTests/Image/PatchTests.swift

OIST dataset loader

---

Examples/OISTVisualizationTool/main.swift
Sources/BeeDataset/OISTBeeVideo.swift
Tests/BeeDatasetTests/OISTDatasetTests.swift

I uploaded 20 tracks to GCS. This PR adds code that downloads the tracks from GCS and that loads them into memory.
My process for creating the tracks was:
1. Build candidate tracks by joining the nearest bounding boxes in consecutive frames.
2. Manually go through the results and select valid subsequences of the candidate tracks.

OIST video tracks

---

Examples/BeeTrackingTool/main.swift
Sources/BeeDataset/OISTBeeVideo.swift
Sources/BeeTracking/TrackingFactorGraph.swift
Sources/BeeTracking/TrackingMetrics.swift
Sources/SwiftFusion/Image/OrientedBoundingBox.swift
Tests/BeeTrackingTests/TrackingMetricsTests.swift
Tests/SwiftFusionTests/Image/OrientedBoundingBoxTests.swift

Functions and datastructures that take (dataset, tracker) and produce evaluation metrics:
* accuracy and robustness as in VOT 2020
* expected average overlap as in VOT 2020
* I'll add Pose/Orientation/Translation metrics in a later PR tomorrow.
You must install the "shapely" python library on your system to use this.
The metric calculators have tests and also I tried it on a real dataset and it all seems to work correctly.
Here is a notebook demonstrating usage: https://colab.sandbox.google.com/drive/1avFw27ZIU6fR1IZ4PAYHCqOCI5QX3_yV#scrollTo=QL9N6iijCZe_

tracker evaluation metrics

---

Sources/BeeTracking/FrameStatistics.swift
Sources/BeeTracking/OISTBeeVideo+Batches.swift
Tests/BeeTrackingTests/OISTBeeVideo+BatchesTests.swift

The test tests that this returns a batch.
I have manually verified that the batches have background patches in them.

sample background images

---

Examples/OISTVisualizationTool/Util.swift
Examples/OISTVisualizationTool/main.swift
Sources/BeeTracking/NaiveBayesAETracker.swift

makeNaiveBayesAETracker in its own file

---

Sources/BeeTracking/TrackingMetrics.swift

Here is some documentation that was missing from my original commit.

add some documentation to TrackingMetrics.swift

---

Package.swift
Scripts/Fan02.swift
Scripts/Fan04.swift
Sources/SwiftFusion/Inference/IdentityProjection.swift
Sources/SwiftFusion/Inference/PCAEncoder.swift
Tests/SwiftFusionTests/Inference/PCAEncoderTests.swift

This is the fixes picked from the kitchen sink

[1/5] Fixed warnings and wrong PCAEncoder

---

Sources/BeeTracking/TrackingLikelihoodModel.swift
Sources/SwiftFusion/Inference/LatentAppearanceTrackingFactor.swift

This PR should fix the EM importance sampling.

Fix the EM importance sampling
