- Sources/DiffSwiftTest/Core/JacobianProtocol.swift
- Sources/DiffSwiftTest/Geometry/Point2.swift
- Sources/DiffSwiftTest/Geometry/Pose2.swift
- Tests/DiffSwiftTestTests/Core/JacobianProtocolTests.swift
This PR added simple inference for `basisVectors` so you can just write `jacobian(of: at:)` instead of `jacobian(of: at: basisVectors:)`.
> Simplified interface for Double jacobians

- Sources/SwiftFusion/Core/Jacobian.swift
- Sources/SwiftFusion/Core/StandardBasis.swift
- Sources/SwiftFusion/Geometry/Point2.swift
- Sources/SwiftFusion/Geometry/Pose2.swift
- Sources/SwiftFusion/Geometry/Rot2.swift
- Tests/SwiftFusionTests/Core/JacobianTests.swift
- Tests/SwiftFusionTests/XCTestManifests.swift
This adds a `TangentStandardBasis` protocol that defines a basis for the tangent space of a type. This protocol allows us to unify all the `jacobian` functions into one function that works for all types.
It would be simpler to have a `StandardBasis` protocol that defines a basis for a vector space, and then conform `TangentVector` to `StandardBasis`. But we can't do that right now because of https://bugs.swift.org/browse/TF-1227. I think we should do that after https://bugs.swift.org/browse/TF-1227 gets fixed.
This resolves #13.
> Unified jacobian protocol

- Sources/SwiftFusion/Core/Jacobian.swift
- Sources/SwiftFusion/Geometry/Pose2.swift
- Sources/SwiftFusion/Geometry/Rot2.swift
- Tests/SwiftFusionTests/Core/JacobianTests.swift
- Tests/SwiftFusionTests/Geometry/Pose2Tests.swift
- Tests/SwiftFusionTests/Geometry/Rot2Tests.swift
* Adds `public` to some properties and functions that clients (e.g. some example colab notebooks that I am writing) might want to use.
* Removes `@testable import` from the tests, so that the tests test the public interface. If there's ever a case where we really do want to test a private function we could put that test in a separate file.
* Adds `@differentiable` to `Pose2.*`.
* Adds missing closing paren to `Rot2.debugDescription`.
> small fixes to public interface

- Sources/SwiftFusion/Core/Dictionary+Differentiable.swift
- Tests/SwiftFusionTests/Core/Dictionary+DifferentiableTests.swift
- Tests/SwiftFusionTests/XCTestManifests.swift
As discussed in https://github.com/borglab/SwiftFusion/pull/23/files/eea06d0b6c3fca7c6bba2ebe6588097f0096dc36#r405894624, it would be nice for `Dictionary` to be `Differentiable`.
I will work on getting this included in the standard library so that it does not need to exist in this repo, but it will take weeks-months for that to make it into a release toolchain, so in the meantime you probably want it in this repo so that you can use it sooner.
This PR only defines a derivative for the "subscript" operation. We'll need to define derivatives for any other primitive dictionary operations that you need. But it looks like "subscript" is all you need in the short term.
> make Dictionary Differentiable

- Sources/SwiftFusion/Core/AnyDifferentiable.swift
- Tests/SwiftFusionTests/Core/AnyDifferentiableTests.swift
- Tests/SwiftFusionTests/XCTestManifests.swift
Adds an `AnyDifferentiable` type that allows us to take derivatives with respect to type-erased differentiable types.
Includes a test that demonstrates how to take the derivative with respect to an array that contains `Pose2` and `Vector2` elements.
NOTE: This will be available in S4TF v0.9, so we should delete this as soon as we switch to that version.
Resolves #30
> import AnyDifferentiable

- .github/workflows/ci.yml
- Sources/SwiftFusion/Core/LieGroup.swift
- Sources/SwiftFusion/Core/TensorConvertible.swift
- Sources/SwiftFusion/Inference/BetweenFactor.swift
- Sources/SwiftFusion/Inference/PriorFactor.swift
This partially reverts commit 87e759809160228e98f93da0c406ba76b5d97b65.
[TF-1234](https://bugs.swift.org/browse/TF-1234) is fixed, so we can revert workarounds and restore idiomatic code.
---
*Please do not merge until the [TF-1234](https://bugs.swift.org/browse/TF-1234) fix (https://github.com/apple/swift/pull/31670) is merged and new toolchains are released.* This patch won't build with current toolchains missing the fix.
I'm building a macOS toolchain with the fix right now, to be shared asap.
---
Aside: could I please have edit access to borglab/SwiftFusion? We agreed to develop on borglab/SwiftFusion branches instead of using forks.
> Revert TF-1234 workarounds.

- Sources/SwiftFusion/Geometry/Pose3.swift
- Sources/SwiftFusion/Geometry/Rot3.swift
There seem to be one or more control flow differentiation bugs causing incorrect derivatives for `Pose3.local` and `Rot3.local`.
I filed https://bugs.swift.org/browse/SR-12776 to fix them.
In the meantime, these changes seem to make the derivative correct.
> work around control flow differentiation bug

- Examples/Pose2SLAMG2O/main.swift
- Sources/SwiftFusion/Core/Matrix.swift
- Sources/SwiftFusion/Core/Vector.swift
- Sources/SwiftFusion/Core/VectorN.swift
- Sources/SwiftFusion/Core/VectorN.swift.gyb
- Sources/SwiftFusion/Inference/BetweenFactor.swift
- Sources/SwiftFusion/Inference/Errors.swift
- Sources/SwiftFusion/Inference/JacobianFactor.swift
- Sources/SwiftFusion/Inference/NonlinearFactorGraph.swift
- Sources/SwiftFusion/Inference/PriorFactor.swift
- Sources/SwiftFusion/Inference/VectorValues.swift
- Tests/SwiftFusionTests/Core/MatrixTests.swift
- Tests/SwiftFusionTests/Core/TensorFlowMatrixTests.swift
- Tests/SwiftFusionTests/Core/VectorNTests.swift
- Tests/SwiftFusionTests/Core/VectorNTests.swift.gyb
- Tests/SwiftFusionTests/Core/VectorTests.swift
- Tests/SwiftFusionTests/Inference/GaussianFactorGraphTests.swift
- Tests/SwiftFusionTests/Inference/NonlinearFactorGraphTests.swift
- Tests/SwiftFusionTests/Optimizers/CGLSTests.swift
- Tests/SwiftFusionTests/TestUtilities.swift
- Tests/SwiftFusionTests/XCTestManifests.swift
- generate.sh
This PR adds array-backed `Vector` and `Matrix` types, and replaces most uses of `Tensor` with them.
I renamed the existing `Vector.swift.gyb` to `VectorN.swift.gyb`, so that I could free up the name `Vector.swift` for the dynamically-sized `Vector` type.
This gives me a 15x speedup on CGLS: before, 200 iterations of CGLS on INTEL took 90s; after, they take 6s. This is not the full 900x speedup that I mentioned in https://github.com/borglab/SwiftFusion/issues/42#issuecomment-626142882 because the full speedup involves more changes and I wanted to keep this PR as small as possible.
> replace Tensor with array-backed Vector and Matrix

- Examples/Pose2SLAMG2O/main.swift
- Sources/SwiftFusion/Geometry/Rot3.swift
- Sources/SwiftFusion/Inference/BetweenFactor.swift
- Sources/SwiftFusion/Inference/JacobianFactor.swift
- Sources/SwiftFusion/Inference/PriorFactor.swift
- Sources/SwiftFusion/Inference/Values.swift
- Tests/SwiftFusionTests/Geometry/Pose3Tests.swift
- Tests/SwiftFusionTests/Inference/NonlinearFactorGraphTests.swift
(This is https://github.com/borglab/SwiftFusion/pull/49, rebased to feature/nlfg_with_manifold. I'm pasting the same description below.)
This sets `Values.TangentVector` to `VectorValues`, which allows a few nice improvements to the APIs:
* To update a `Value` using a `VectorValues`, now all you need is `vals.move(along: vectorval)` instead of needing to loop over all the components and cast them.
* We can now write a generic `JacobianFactor` initializer that linearizes any error function, which simplifies the implementation of `linearize`.
Other API changes:
* Now you access values using `vals[key, as: Pose2.self]` instead of `vals[key].baseAs(Pose2.self)`. This is necessary so that `Values` knows what type you are accessing and therefore knows how to convert its tangent vector to a …
> Make Values.TangentVector == VectorValues

- Sources/SwiftFusion/Core/EuclideanVectorSpace.swift
- Sources/SwiftFusion/Core/LieGroup.swift
- Sources/SwiftFusion/Core/Vector.swift
- Sources/SwiftFusion/Geometry/Pose2.swift
- Sources/SwiftFusion/Geometry/Pose3.swift
- Sources/SwiftFusion/Geometry/Rot2.swift
* Add `squaredNorm` requirement to `EuclideanVectorSpace`, so that we can ask for its norm generically.
* Add constraint that the `VectorSpaceScalar == Double` because we seem to be using `Double` everywhere and this constraint makes it easier. (We can relax the constraint later if we switch to generic floating point types.)
* Add a group identity requirement to `LieGroup`.
> small math improvements

- Sources/SwiftFusion/Core/LieGroup.swift
- Sources/SwiftFusion/Core/Manifold.swift
- Sources/SwiftFusion/Geometry/Pose2.swift
- Sources/SwiftFusion/Geometry/Pose3.swift
- Sources/SwiftFusion/Geometry/Rot2.swift
- Sources/SwiftFusion/Geometry/Rot3.swift
- Sources/SwiftFusion/Inference/BetweenFactor.swift
- Sources/SwiftFusion/Inference/PriorFactor.swift
- Tests/SwiftFusionTests/Geometry/Pose2Tests.swift
- Tests/SwiftFusionTests/Geometry/Rot3Tests.swift
This makes lie groups slightly easier to define, and also makes their derivatives faster. Specifically:
* Now you only need to define the manifold operations (`localCoordinate`, `retract`) and group operations (identity, inverse, group op) on the `ManifoldCoordinate`. The `Manifold` type gets them automatically.
* I added derivatives for all these operations that use the mathematical structure to be simpler and more efficient.
One result is a pretty big speedup in the Pose3SLAM test:
* Before: 12.097 seconds
* After: 8.249 seconds
> default implementations of lie group and manifold operations, with faster derivatives

- .gitignore
- Package.resolved
- Package.swift
- README.md
- Sources/Benchmarks/Pose2SLAM.swift
- Sources/Benchmarks/main.swift
- Sources/SwiftFusion/Datasets/DatasetCache.swift
- Sources/SwiftFusion/Datasets/G2OReader.swift
This adds a benchmark for Pose2SLAM using NonlinearFactorGraph, Gauss-Newton, and CGLS.
I added a section of the readme showing how to run it.
Since this adds an external dependency, I committed a `Package.resolved` that pins us to a specific commit. `swift package update` updates this to newer commits.
> benchmarking infrastructure

- Sources/SwiftFusion/Geometry/Pose3.swift
- Sources/SwiftFusion/Geometry/Rot2.swift
As I mentioned in https://github.com/borglab/SwiftFusion/pull/66, the Swift typechecker is slow when there are overloaded operators.
We can speed it up without figuring out all the answers in that discussion by giving the compiler hints that help it resolve the overloads.
Before:
```
marcrasi@marcrasi:~/git/SwiftFusion$ swift package clean && time swift build
[88/88] Linking Benchmarks
real    0m27.196s
user    1m54.372s
sys     0m5.155s
```
After:
```
marcrasi@marcrasi:~/git/SwiftFusion$ swift package clean && time swift build
[88/88] Linking Benchmarks
real    0m12.526s
user    1m39.393s
sys     0m4.367s
```
For future reference, I found the offending expressions with:
```
swift package clean && swift build -Xswiftc -Xfrontend -Xswiftc -debug-time-function-bodies > compile_times.txt …
```
> help the typechecker go faster

- Package.resolved
- Package.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
- Tests/SwiftFusionTests/Inference/ValuesStorageTests.swift
This storage will be used to store differentiable and vector values for factor graph variable assignments and for factor graph error vectors.
This uses the Penguin ArrayStorage data structure, and this is modeled on the [example here](https://github.com/saeta/penguin/blob/master/Tests/PenguinStructuresTests/ArrayStorageExtensionTests.swift).
This doesn't include the user-facing wrapper that manages these and lets users store values of multiple different types.
(@ProfFan, @dellaert, here is the first in a series of small incremental PRs for the real implementation of the generic factor graph prototype that I showed you ~2 weeks ago. I want to get reviews on each of the small pieces, and @dabrahams has agreed to review them, so you can pay as much or as little attention as you like to the …
> Add type-erased contiguous storage for `Differentiable` and `EuclideanVector` types.

- Package.resolved
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/GenericFactor.swift
- Sources/SwiftFusion/Inference/ValuesArray.swift
- Tests/SwiftFusionTests/Inference/GenericFactorTests.swift
(This is a PR on top of https://github.com/borglab/SwiftFusion/pull/73).
Adds:
* a `Factor` protocol that lets you declare factors with arbitrary input types and an error function that computes an error based on the input
* `AnyFactorStorage` for type-erased storage of `Factor`s
* `AnyFactorStorage.errors`, which calculates errors for all factors in an `AnyFactorStorage`. (This works very efficiently, by doing pointer arithmetic into contiguous buffers of input values.)
Credit: Uses lots of ideas and code that @dabrahams shared with me.
There is a test demonstrating how to use it.
Note that this is missing all the sugar that will make it nicer to declare and use factors. I'll do that in subsequent PRs.
> generic Factor protocol

- Package.resolved
- Package.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/GenericFactor.swift
- Sources/SwiftFusion/Inference/ValuesArray.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
- Tests/SwiftFusionTests/Inference/GenericFactorTests.swift
- Tests/SwiftFusionTests/Inference/ValuesStorageTests.swift
`ArrayBuffer` is the value-semantic container for `ArrayStorage`, and we should be using `ArrayBuffer` everywhere. This PR updates everything to use `ArrayBuffer`.
This depends on https://github.com/saeta/penguin/pull/70.
> update generic factor graph to use ArrayBuffer

- Package.resolved
- Package.swift
- Sources/Benchmarks/Pose2SLAM.swift
- Sources/SwiftFusion/Datasets/G2OReader.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/GenericBetweenFactor.swift
- Sources/SwiftFusion/Inference/GenericFactor.swift
- Sources/SwiftFusion/Inference/GenericFactorGraph.swift
- Sources/SwiftFusion/Inference/GenericGaussianFactorGraph.swift
- Sources/SwiftFusion/Inference/GenericJacobianFactor.swift
- Sources/SwiftFusion/Inference/GenericPriorFactor.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
- Sources/SwiftFusion/Inference/VariableAssignments.swift
- Sources/SwiftFusion/Optimizers/CGLS.swift
- Tests/SwiftFusionTests/Inference/GenericFactorGraphTests.swift
- Tests/SwiftFusionTests/Inference/GenericFactorTests.swift
Adds:
* `VariableAssignments` methods that make it nicer and easier to use.
* `GenericFactorGraph` and `GenericGaussianFactorGraph` with high-level methods that make it easy to build a graph and linearize it.
* `GenericJacobianFactor` for linearizing factors.
* `GenericPriorFactor` and `GenericBetweenFactor` for the Pose2SLAM problem.
* A `Pose2SLAM` benchmark using all of the above.
To run the benchmark: `swift build -c release -Xswiftc -cross-module-optimization && .build/release/Benchmarks --filter GenericFactorGraph`
> Pose2SLAM benchmark with GenericFactorGraph

- Sources/SwiftFusion/Inference/AllVectors.swift
- Sources/SwiftFusion/Inference/NewFactor.swift
- Sources/SwiftFusion/Inference/NewGaussianFactorGraph.swift
- Sources/SwiftFusion/Inference/ScalarJacobianFactor.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
- Sources/SwiftFusion/Inference/VariableAssignments.swift
- Tests/SwiftFusionTests/Inference/NewGaussianFactorGraphTests.swift
- Tests/SwiftFusionTests/Inference/ValuesStorageTests.swift
This implements the `addScalarJacobians` method, which lets you add scalar jacobians over all variables to any gaussian factor graph.
Eventually it would probably be good to have a more general-purpose API instead, like:
```
let jacobians = factorGraph.inputVariableIds.map { id in
ScalarJacobianFactor(id, scalar: 0.1)
}
factorGraph.add(jacobians)
```
But for now I think this method does what you need.
> scalar jacobians

- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/NewBetweenFactor.swift
- Sources/SwiftFusion/Inference/NewJacobianFactor.swift
- Sources/SwiftFusion/Inference/NewPriorFactor.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
I realized that it might not be clear how to get the prior and between factors working with Pose3. The `JacobianRows` type parameter is non obvious and not documented. So I added some doc comments about that.
Also I added some specializations that you will need for Pose3SLAM to be fast, and comments about them.
> add documentation about jacobians and specializations

- Sources/Benchmarks/Pose3SLAM.swift
- Sources/SwiftFusion/Geometry/Pose3.swift
- Tests/SwiftFusionTests/Geometry/Pose3Tests.swift
I changed the Pose3SLAM benchmark to use sphere2500 instead of pose3example because pose3example is so small that I was getting very noisy benchmark results.
Results from the sphere2500 benchmark:
* Before: 108s
* After: 20s
> add Pose3 custom Adjoint, to make Pose3SLAM faster

- Sources/SwiftFusion/Inference/NewFactorGraph.swift
- Sources/SwiftFusion/Optimizers/LM.swift
Fixes some problems with LM convergence in some cases:
* LM was calling CGLS with precision 0, which caused numerical errors to get really big when CGLS tried to optimize things beyond a sensible precision. I changed the precision to 1e-10. (Maybe it should be configurable).
* LM was comparing nonlinear error with linearized error to calculate "model fidelity". LM was using `graph.errors(at: x)` to calculate nonlinear error. But `graph.errors(at: x)` includes errors from discrete factors that do not appear in the linearized error, so it's not comparable with the linearized error. I added `graph.linearizableErrors(at: x)` that computes nonlinear errors for all the linearizable factors.
> fix LM convergence

- Sources/SwiftFusion/Core/EuclideanVectorN.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/NewJacobianFactor.swift
- Sources/SwiftFusionBenchmarks/Pose2SLAM.swift
- Sources/SwiftFusionBenchmarks/Pose3SLAM.swift
Adds more specializations, and changes some particularly hot code to use pointers instead of collections.
Makes Pose2SLAM ~4x faster and Pose3SLAM ~3x faster.
Before:
```
swift build -c release -Xswiftc -cross-module-optimization && .build/release/Benchmarks --filter NewFactorGraph
name                                                                    time             std        iterations
--------------------------------------------------------------------------------------------------------------
Pose2SLAM: NewFactorGraph, Intel, 10 Gauss-Newton steps, 500 CGLS steps  1868228204.0 ns ±   0.00 %          1
Pose3SLAM: NewFactorGraph, sphere2500, 30 LM steps, 200 CGLS steps      19669232876.0 ns ±   0.00 %          1
```
After:
```
swift build -c release -Xswiftc …
```
> speed up the new factor graphs

- Package.resolved
- Sources/SwiftFusion/Inference/AllVectors.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/NewFactor.swift
- Sources/SwiftFusion/Inference/NewFactorGraph.swift
- Sources/SwiftFusion/Inference/NewGaussianFactorGraph.swift
- Sources/SwiftFusion/Inference/PenguinExtensions.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
- Sources/SwiftFusion/Inference/VariableAssignments.swift
- Tests/SwiftFusionTests/Inference/NewFactorTests.swift
- Tests/SwiftFusionTests/Inference/ValuesStorageTests.swift
- Tests/SwiftFusionTests/Inference/VariableAssignmentsTests.swift
Migrates everything to the new `ArrayBuffer` interface from https://github.com/saeta/penguin/pull/82.
The boilerplate in `ValuesStorage` and `FactorsStorage` feels simpler now, which is good!
Benchmarks before:
```
swift build -c release -Xswiftc -cross-module-optimization && .build/release/SwiftFusionBenchmarks --filter NewFactorGraph
name                                                                   time           std        iterations
-----------------------------------------------------------------------------------------------------------
Pose2SLAM.NewFactorGraph, Intel, 10 Gauss-Newton steps, 500 CGLS steps  456.792364 ms ±   0.00 %          1
Pose3SLAM.NewFactorGraph, sphere2500, 30 LM steps, 200 CGLS steps      5922.074432 ms ±   0.00 %          1
```
Benchmarks after:
``` …
```
> Migrate to new ArrayBuffer

- Sources/SwiftFusion/Inference/FactorGraph.swift
- Sources/SwiftFusion/Inference/VariableAssignments.swift
- Tests/SwiftFusionTests/Inference/FactorGraphTests.swift
Example usage:
```
for f in graph.factors(type: PriorFactor2.self) {
print(f)
}
```
> add method for getting factors from factor graph

- Package.resolved
- Sources/SwiftFusion/Core/EuclideanVectorN.swift
- Sources/SwiftFusion/Core/FixedSizeMatrix.swift
- Tests/SwiftFusionTests/Core/FixedSizeMatrixTests.swift
Implements a `FixedSizeMatrix` supporting the operations described in https://github.com/borglab/SwiftFusion/issues/105.
This is pretty quick and dirty, just to get something useful working.
Let me know if it's missing anything or if there are more operations you'd like. Do you need differentiability? I'm happy to add anything you need :)
> quick and simple fixed size matrix

- Sources/SwiftFusion/Datasets/G2OReader.swift
- Sources/SwiftFusion/Inference/BetweenFactor.swift
- Sources/SwiftFusion/Inference/BetweenFactorAlternative.swift
- Sources/SwiftFusion/Inference/Factor.swift
- Sources/SwiftFusion/Inference/PriorFactor.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
- Sources/SwiftFusion/Inference/VariableAssignments.swift
- Tests/SwiftFusionTests/Inference/FactorGraphTests.swift
- Tests/SwiftFusionTests/Inference/FactorTests.swift
- Tests/SwiftFusionTests/Inference/VariableAssignmentsTests.swift
We never use anything other than `Int` as the second type parameter, so we can remove it to make it easier to type.
> change TypedID<X, Int> to TypedID<X>

- Examples/Pose3SLAMG2O/main.swift
- Sources/SwiftFusion/Datasets/G2OReader.swift
- Sources/SwiftFusion/Inference/AllVectors.swift
- Sources/SwiftFusion/Inference/BetweenFactor.swift
- Sources/SwiftFusion/Inference/BetweenFactorAlternative.swift
- Sources/SwiftFusion/Inference/ChordalInitialization.swift
- Sources/SwiftFusion/Inference/Factor.swift
- Sources/SwiftFusion/Inference/FactorBoilerplate.swift
- Sources/SwiftFusion/Inference/FactorBoilerplate.swift.gyb
- Sources/SwiftFusion/Inference/FactorGraph.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/JacobianFactor.swift
- Sources/SwiftFusion/Inference/PriorFactor.swift
- Sources/SwiftFusion/Inference/ScalarJacobianFactor.swift
- Sources/SwiftFusionBenchmarks/Pose2SLAM.swift
- Sources/SwiftFusionBenchmarks/Pose3SLAM.swift
- Tests/SwiftFusionTests/Inference/ChordalInitializationTests.swift
- Tests/SwiftFusionTests/Inference/FactorGraphTests.swift
- Tests/SwiftFusionTests/Inference/FactorTests.swift
- Tests/SwiftFusionTests/Optimizers/LMTests.swift
- generate.sh
See `BetweenFactor.swift` for an example of the reduced boilerplate.
> fixed-arity protocols that reduce boilerplate

- Sources/SwiftFusionBenchmarks/Pose2SLAM.swift
This benchmark is failing because of the recent "0.5" factor added to the errors.
> fix benchmark assertion

- Sources/SwiftFusion/Inference/IdentityLinearizationFactor.swift
- Tests/SwiftFusionTests/Inference/IdentityLinearizationFactorTests.swift
A factor that makes it possible to linearize any `GaussianFactor` without doing any real work.
Requested by @dabrahams for a thing he is working on.
> identity linearization factor

- Sources/SwiftFusion/Core/EuclideanVector.swift
- Sources/SwiftFusion/Core/EuclideanVectorN.swift
- Sources/SwiftFusion/Core/FixedShapeTensor.swift
- Sources/SwiftFusion/Geometry/Pose2.swift
- Tests/SwiftFusionTests/Core/AnyDifferentiableTests.swift
- Tests/SwiftFusionTests/Core/EuclideanVectorTests.swift
- Tests/SwiftFusionTests/Core/FixedShapeTensorTests.swift
- Tests/SwiftFusionTests/Geometry/Pose2Tests.swift
- Tests/SwiftFusionTests/Geometry/Pose3Tests.swift
- Tests/SwiftFusionTests/Geometry/Rot3Tests.swift
- Tests/SwiftFusionTests/Inference/ChordalInitializationTests.swift
- Tests/SwiftFusionTests/Inference/FactorGraphTests.swift
- Tests/SwiftFusionTests/Optimizers/CGLSTests.swift
* Adds differentiable `init(flatTensor:)` and `.flatTensor` for converting fixed size vectors from/to `Tensor`, so that we can "escape" to `TensorFlow`-land in calculations that need `TensorFlow` functions.
* Adds `FixedShapeTensor` so that we can use `Tensor`s as variables and error vectors in factor graphs.
> make it possible to use `Tensor` in factor graphs

- Package.resolved
- Package.swift
- Sources/SwiftFusion/Inference/BetweenFactorAlternative.swift
- Sources/SwiftFusion/Inference/ChordalInitialization.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/JacobianFactor.swift
- Tests/SwiftFusionTests/Inference/ChordalInitializationTests.swift
My main motivation for this is so that we can have factors with big error vectors (on the order of 1,000 to 10,000 dimensions) without having to define fixed size arrays up to Array10000. We want to have error vectors with one element per pixel in an image.
Oddly, this also gave a 3% speedup in one of the benchmarks by changing the fixed size `Array6` to the dynamic `Array`. (See comment for details). Maybe it's avoiding some slow copies by passing around a pointer to the data.
This depends on a Penguin PR that I will create soon.
> use dynamically allocated array for big jacobians

- Sources/SwiftFusion/Geometry/Pose2.swift
The new S4TF v0.11 release fails to compile this without the explicit typealias.
> add explicit TangentVector to Pose2

- Sources/SwiftFusion/MCMC/RandomWalkMetropolis.swift
- Tests/SwiftFusionTests/MCMC/MCMCTests.swift
Use a pseudo-random number generator instead of the system one.
> Make MCMC tests stop failing nondeterministically.

- Package.resolved
- Package.swift
swift-models versions later than this commit break us with "error: swift-benchmark is required using two different revision-based requirements (master and f70bf472b00aeaa05e2374373568c2fe459c11c7), which is not supported".
Eventually we should figure out a way to fix swift-models, but for now, this change makes us compile successfully.
> fix swift-models dependency

- Sources/SwiftFusion/Image/ArrayImage.swift
- Sources/SwiftFusion/Image/Patch.swift
- Sources/SwiftFusionBenchmarks/Patch.swift
- Tests/SwiftFusionTests/Image/ArrayImageTests.swift
- Tests/SwiftFusionTests/Image/PatchTests.swift
This makes the crop faster in a few ways:
* Do the crop on an `Array`, which has faster indexing than a `Tensor`.
* Do the derivative only with respect to the bounding box position, so that we don't spend time calculating the derivative with respect to the input image.
* Do the pullback with a custom vjp that is more efficient than the synthesized vjp.
@ProfFan this is just the speedups that I have already shown you. I have some additional speedups that I'll put in a separate PR soon.
> faster crop

- Tests/SwiftFusionTests/Inference/ValuesStorageTests.swift
- Tests/SwiftFusionTests/TestUtilities.swift
Newer compilers produce a warning that this change removes.
> Fix #filePath mis-threading

- Tests/BeeDatasetTests/BeeDatasetTests.swift
- Tests/SwiftFusionTests/TestUtilities.swift
* https://github.com/borglab/SwiftFusion/pull/166 fixed warnings on newer toolchains, but now it warns on older toolchains. I added parentheses to suppress warnings on the older toolchains.
* We were using `#file` to get the paths of some test fixtures. This will eventually stop working because of [SE-0274](https://github.com/apple/swift-evolution/blob/master/proposals/0274-magic-file.md). So I changed these to `#filePath`.
Fixes #169.
> #filePath fixes

- Sources/SwiftFusion/Core/Dictionary+Differentiable.swift
- Sources/SwiftFusion/Core/FixedSizeMatrix.swift
- Sources/SwiftFusion/Core/LieGroup.swift
- Sources/SwiftFusion/Core/Manifold.swift
- Sources/SwiftFusion/Core/Tuple+Vector.swift
- Sources/SwiftFusion/Core/Vector.swift
- Sources/SwiftFusion/Image/Patch.swift
- Sources/SwiftFusion/Inference/AnyArrayBuffer+Differentiable.swift
- Sources/SwiftFusion/Inference/ArrayBuffer+Tensor.swift
- Sources/SwiftFusion/Inference/ArrayBuffer+Vector.swift
- Sources/SwiftFusion/Inference/JacobianFactor.swift
- Sources/SwiftFusion/Inference/PenguinExtensions.swift
3.3% speedup on Pose3SLAM benchmark.
1.1% on Pose2SLAM
> Eliminate as many uses of `static var zero` as possible

- Sources/SwiftFusion/Geometry/Pose2.swift
- Sources/SwiftFusion/Geometry/Pose3.swift
- Sources/SwiftFusion/Geometry/Rot2.swift
- Sources/SwiftFusion/Geometry/Rot3.swift
- Tests/SwiftFusionTests/Geometry/Pose2Tests.swift
- Tests/SwiftFusionTests/Geometry/Pose3Tests.swift
- Tests/SwiftFusionTests/Geometry/Rot2Tests.swift
- Tests/SwiftFusionTests/Geometry/Rot3Tests.swift
`Rot2`:
`Rot3`:
`Pose2`:
`Pose3`:
> Improve group actions

- Sources/SwiftFusion/MCMC/RandomWalkMetropolis.swift
- Tests/SwiftFusionTests/MCMC/MCMCTests.swift
Addresses, but by itself does not fix, #143.  Currently, the test fails deterministically.
@dellaert please take a look and make sure the test is correct.
> Remove more nondeterminism in MCMC test

- Package.resolved
- Package.swift
- Sources/SwiftFusion/Core/FixedShapeTensor.swift
- Sources/SwiftFusion/Inference/ArrayBuffer+Vector.swift
- Sources/SwiftFusion/Inference/ValuesStorage.swift
- Tests/SwiftFusionTests/Core/FixedShapeTensorTests.swift
- Tests/SwiftFusionTests/Core/FixedSizeMatrixTests.swift
- Tests/SwiftFusionTests/Core/VectorNTests.swift
- Tests/SwiftFusionTests/Core/VectorNTests.swift.gyb
- Tests/SwiftFusionTests/Core/VectorTests.swift
- Tests/SwiftFusionTests/Inference/AnyArrayBufferTests.swift
Adds a `checkVectorSemantics` method that checks the recently-added `Scalars` and `scalars` requirements.
Migrates all the existing vector semantics checks to be inside of `checkVectorSemantics` too.
> test vector semantics

- Sources/SwiftFusion/Core/VectorN.swift
- Sources/SwiftFusion/Core/VectorN.swift.gyb
- Sources/SwiftFusion/Inference/ArrayBuffer+Vector.swift
Otherwise code after yield won't run when the yielded-to code throws:
https://forums.swift.org/t/modify-accessors/31872/280
(`_fixLifetime` doesn't technically need to move, but it's best to be uniform).
> defer all code that must run post-yield.

- .github/workflows/ci.yml
- Package.resolved
- Sources/SwiftFusion/Core/Vector.swift
- Sources/SwiftFusion/Inference/PenguinExtensions.swift
https://github.com/saeta/penguin/pull/120 moved these into Penguin.
For some reason, defining them in both places causes a compiler crash.
This PR fixes https://github.com/borglab/SwiftFusion/issues/194.
> remove algorithms that are in penguin now

- Package.resolved
- Sources/SwiftFusion/Core/TypeKeyedArrayBuffers.swift
- Sources/SwiftFusion/Inference/PenguinExtensions.swift
Deterministic ordering will be needed for several reasons: one is for making TypeKeyedArrayBuffers of Vectors into Vectors themselves (need a stable scalar ordering), another is for stability of floating point results in tests (@marcrasi has more details).
> Use insertion ordered dictionary in TypeKeyedArrayBuffers

- Examples/BeeTrackingTool/main.swift
- Package.swift
- Sources/BeeTracking/AppearanceRAE+Serialization.swift
- Sources/BeeTracking/AppearanceRAE.swift
- Sources/BeeTracking/FrameStatistics.swift
- Sources/BeeTracking/TrackingFactorGraph.swift
- Tests/BeeTrackingTests/AppearanceRAETests.swift
This adapts pieces of https://colab.sandbox.google.com/drive/1cE0gvS4KADvoX2xF6js6LopsE51vg9do#scrollTo=k_kr6IL2d-e0 into a module "BeeTracking" and a binary "BeeTrackingTool" that runs model training and factor graph inference.
My next step will be to try to profile it and make it faster. My initial attempts at profiling just say it's spending a bunch of time in "libx10", without giving any information about what it's doing there, and this isn't very useful. So I'll try to get some more useful profiles.
> add RAE bee tracking model

- Sources/SwiftFusion/Inference/AppearanceTrackingFactor.swift
- Sources/SwiftFusion/Inference/Factor.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/PPCATrackingFactor.swift
This adds a `static func linearized` to the Factor protocol, with a default implementation that does the default linearization using AD. This allows conformances to customize the linearization. This replaces the ad-hoc code that we had in FactorsStorage.swift that gave certain specific factors custom linearizations.
I'm planning to use this for my performance work in https://github.com/borglab/SwiftFusion/pull/202, but it's complicated and self-contained enough that I thought it should be a separate PR too.
> generalize mechanism for custom linearizations

- Examples/BeeTrackingTool/main.swift
- Package.swift
- Sources/BeeTracking/TrackingFactorGraph.swift
- Sources/SwiftFusion/Core/Timer.swift
- Sources/SwiftFusion/Inference/AppearanceTrackingFactor.swift
- Sources/SwiftFusion/Inference/FactorGraph.swift
- Sources/SwiftFusion/Inference/FactorsStorage.swift
- Sources/SwiftFusion/Inference/PPCA.swift
- Sources/SwiftFusion/Optimizers/CGLS.swift
- Sources/SwiftFusion/Optimizers/LM.swift
- Tests/BeeDatasetTests/BeePPCATests.swift
- Tests/SwiftFusionTests/Inference/PPCATests.swift
This does a bunch of simple things to make tracking faster. Each LM iteration takes ~1s on my machine now, which is much faster than it used to be.
Specific changes:
* Added some timing code because I couldn't get pprof to give me useful information about what was happening.
* Decreased the CGLS precision because it was spending most of the time in CGLS and it doesn't seem useful to spend tons of time for a tiny bit of precision. This was the biggest speedup.
* Split the appearance model from the appearance model jacobian so that we don't uselessly compute the jacobian when we just need the error.
* Run some embarrassingly parallel things in parallel.
> make tracking faster

- Sources/SwiftFusion/Geometry/Cal3_S2.swift
- Sources/SwiftFusion/Geometry/CameraCalibration.swift
- Sources/SwiftFusion/Geometry/PinholeCamera.swift
- Tests/SwiftFusionTests/Geometry/Cal3_S2Tests.swift
- Tests/SwiftFusionTests/Geometry/PinholeCameraTests.swift
Here's my first draft of the pinhole camera implementation. I based the structure on GTSAM. Some notes:
- Personally I feel like the name `Cal3_S2` is a bit confusing. I think the `3` and `2` seem redundant if we consider a camera to be a mapping from 3D world to 2D image, unless we extend the definition of a camera. Also it isn't immediately apparent what the `_S` part means. Maybe change it to something like `SimpleCalibration` or `CalSimple` or `CalSimpleWithSkew`?
- Not all calibration model has a closed-form inverse, especially for the distortion part. Most models are defined in the `uncalibrate()` direction from normalized coordinate to image coordinate. Requiring `calibrate()` in `CameraCalibration` means that some implementations may need to find solution through iteration. It …
> Pinhole camera first draft

- Sources/BeeDataset/OISTBeeVideo.swift
- Tests/BeeDatasetTests/OISTDatasetTests.swift
I found a bug in my recent change to OISTBeeVideo eager loading. It loads the first frame N times instead of loading all N frames.
This PR fixes the bug and adds a test that catches the problem.
I also added a "truncate" option to OISTBeeVideo so that we can load subsets of the video. This makes it possible to run the test quickly, and it should also make it possible to run smaller experiments while we're iterating.
> fix bug in eager OISTBeeVideo loading

- Examples/BeeTrackingTool/main.swift
- Examples/OISTVisualizationTool/main.swift
- Sources/BeeDataset/OISTBeeVideo.swift
- Sources/BeeDataset/VOTVideo.swift
- Sources/BeeDataset/Visualization.swift
- Sources/BeeTracking/FrameStatistics.swift
- Sources/BeeTracking/OISTBeeVideo+Batches.swift
- Sources/BeeTracking/TrackingFactorGraph.swift
- Sources/BeeTracking/TrackingMetrics.swift
- Sources/SwiftFusion/Image/ArrayImage.swift
- Sources/SwiftFusion/Image/Patch.swift
- Sources/SwiftFusion/Inference/AppearanceTrackingFactor.swift
- Sources/SwiftFusion/Inference/ProbablisticTrackingFactor.swift
- Sources/SwiftFusion/Inference/RawPixelTrackingFactor.swift
- Tests/BeeDatasetTests/BeePPCATests.swift
- Tests/SwiftFusionTests/Image/PatchTests.swift
- Tests/SwiftFusionTests/Inference/PPCATests.swift
- Tests/SwiftFusionTests/Inference/ProbablisticTrackingFactorTests.swift
With this PR, `swift run -c release OISTVisualizationTool naive-rae --box-id 8 --verbose` goes from ~6 minutes to ~1 minute for me.
Only like 30s of that is graph inference time.
Main changes:
* Store frames as Float, and do patch in Float, but do all other operations in Double (so that I don't have to change everything to Double, which would be a huge change).
* Store ArrayImage as the measurement in factors instead of Tensor so that we don't have to convert the Tensor to an ArrayImage every time we take a patch.
* Makes `patch` use multithreading.
> ~6x tracking speedup by: removing redundant work, switching images to Float, and parallelizing patch

- .github/workflows/ci.yml
- Package.resolved
- Package.swift
- Sources/BeeDataset/BeeFrames.swift
- Sources/BeeDataset/BeeVideo.swift
- Tests/SwiftFusionTests/Image/PatchTests.swift
* github actions: stop using set-env because it got deprecated (https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
* swift-benchmark: use version instead of commit, so that we don't break when dependencies update their version of swift-benchmark
* swift-models: update to newer commit (can't use version because swift-models doesn't have version tags yet)
* needed to update some calls to a newer signature
* swift-argument-parser: added dependency. we don't directly depend on it but we transitively depend on it, and for some reason swiftpm is getting confused unless I add it to the dependency list.
> clean up and update dependencies

- Sources/SwiftFusion/Geometry/Cal3_S2.swift
- Sources/SwiftFusion/Geometry/CameraCalibration.swift
- Sources/SwiftFusion/Geometry/PinholeCamera.swift
- Tests/SwiftFusionTests/Geometry/PinholeCameraTests.swift
@dan-zheng I've manually implemented the zeroTangentVector functionality for the CameraCalibration object and Cal3_S2 which inherets it. I've run the suite of tests and it works well.
There is still one instance of zeroTangentVector that is being used in the codebase at https://github.com/borglab/SwiftFusion/blob/9eca609c10cdaeb19e34ca047363c183ddad7c3e/Sources/SwiftFusion/Core/LieGroup.swift#L170 that I've had some trouble replacing, but I'll work on it as well. All other uses in the codebase are not being used as Richard Wei mentioned in his issue.
Let me know your thoughts on the current implementation, as well as if you have suggestions on removing the LieGroup zeroTangentVector.
> Removed the use of zeroTangentVector from PinholeCamera
